<?php 

register_field_group(array (
	'id'     => 'acf_informations-film',
	'title'  => 'Informations film',
	'fields' => array (
		array (
			'key'           => 'field_59a152050eca1',
			'label'         => 'Réalisateur',
			'name'          => 'realisateur',
			'type'          => 'text',
			'required'      => 1,
			'default_value' => '',
			'placeholder'   => '',
			'prepend'       => '',
			'append'        => '',
			'formatting'    => 'none',
			'maxlength'     => '',
		),
		array (
			'key'           => 'field_59a152280eca2',
			'label'         => 'Genre',
			'name'          => 'genre',
			'type'          => 'text',
			'required'      => 1,
			'default_value' => '',
			'placeholder'   => '',
			'prepend'       => '',
			'append'        => '',
			'formatting'    => 'none',
			'maxlength'     => '',
		),
		array (
			'key'           => 'field_59a1523e0eca3',
			'label'         => 'Origine',
			'name'          => 'origine',
			'type'          => 'text',
			'required'      => 1,
			'default_value' => '',
			'placeholder'   => '',
			'prepend'       => '',
			'append'        => '',
			'formatting'    => 'none',
			'maxlength'     => '',
		),
		array (
			'key'           => 'field_59a152570eca4',
			'label'         => 'Distributeur',
			'name'          => 'distributeur',
			'type'          => 'text',
			'required'      => 1,
			'default_value' => '',
			'placeholder'   => '',
			'prepend'       => '',
			'append'        => '',
			'formatting'    => 'none',
			'maxlength'     => '',
		),
		array (
			'key'           => 'field_59a152800eca5',
			'label'         => 'Durée',
			'name'          => 'duree',
			'type'          => 'text',
			'required'      => 1,
			'default_value' => '',
			'placeholder'   => '',
			'prepend'       => '',
			'append'        => '',
			'formatting'    => 'none',
			'maxlength'     => '',
		),
		array (
			'key'            => 'field_59a152920eca6',
			'label'          => 'Sortie nationale',
			'name'           => 'sortie_nationale',
			'type'           => 'date_picker',
			'required'       => 1,
			'date_format'    => 'yymmdd',
			'display_format' => 'dd/mm/yy',
			'first_day'      => 1,
		),
		array (
			'key'           => 'field_59a152cd0eca7',
			'label'         => 'Soutien',
			'name'          => 'soutien',
			'type'          => 'text',
			'default_value' => '',
			'placeholder'   => '',
			'prepend'       => '',
			'append'        => '',
			'formatting'    => 'none',
			'maxlength'     => '',
		),
		array (
			'key'           => 'field_59a152eb0eca8',
			'label'         => 'Numéro de visa',
			'name'          => 'numero_de_visa',
			'type'          => 'text',
			'required'      => 1,
			'default_value' => '',
			'placeholder'   => '',
			'prepend'       => '',
			'append'        => '',
			'formatting'    => 'none',
			'maxlength'     => '',
		),
		array (
			'key'           => 'field_59a1531f0eca9',
			'label'         => 'Casting',
			'name'          => 'casting',
			'type'          => 'textarea',
			'required'      => 1,
			'default_value' => '',
			'placeholder'   => '',
			'maxlength'     => '',
			'rows'          => '',
			'formatting'    => 'br',
		),
		array (
			'key'           => 'field_59a153580ecaa',
			'label'         => 'Nominations et récompenses',
			'name'          => 'nominations_et_recompenses',
			'type'          => 'textarea',
			'default_value' => '',
			'placeholder'   => '',
			'maxlength'     => '',
			'rows'          => '',
			'formatting'    => 'br',
		),
	),
	'location' => array (
		array (
			array (
				'param'    => 'post_type',
				'operator' => '==',
				'value'    => 'film',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'options' => array (
		'position'       => 'normal',
		'layout'         => 'default',
		'hide_on_screen' => array (
		),
	),
	'menu_order' => 0,
) );